# Generated by Django 5.0.6 on 2024-05-18 19:05

import django.db.models.deletion
import invoice_api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('description', models.TextField()),
                ('createdAt', models.DateField()),
                ('paymentDue', models.DateField()),
                ('paymentTerms', models.IntegerField()),
                ('clientName', models.CharField(max_length=200)),
                ('clientEmail', models.EmailField(max_length=254)),
                ('senderAddress', models.JSONField()),
                ('clientAddress', models.JSONField()),
                ('items', models.JSONField()),
                ('total', models.DecimalField(decimal_places=2, max_digits=20)),
                ('status', models.ForeignKey(default=invoice_api.models.Status.get_default, on_delete=django.db.models.deletion.CASCADE, to='invoice_api.status')),
            ],
        ),
    ]
